apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    name: discovery
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: discovery